config_id: mdn_voest_realistic
seeds: 42
data_seed: 0

training_hyperparameters:
  early_stopping_patience: 25
  epochs: 500
  clip_gradient_norm: 4.0
  batch_size: 32
  use_lr_scheduler: True
  optimizer_hyperparameters:
    lr: 2.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
  optimizer: adam
  input_noise_x: 0.03
  input_noise_y: 0.03
  loss_hyperparameters:
    reliability_loss_weight: 0.0

    gumbel_tau: 0.01
    sigmoid_steepness: 20
    weights_entropy_loss_weight: 0.0

    loss_calculation_in_normalised_domain: True
  eval_metric_for_best_model: val_nll_loss
  evaluation_function_names: [miscalibration, conformal_prediction]
  slow_first_n_batches: 1
  log_train_every_n: 10
  noisy_start: False
    

data_hyperparameters:
  data_type: voest
  data_path: datasets/voest_datasets/
  original: True
  val_split: 0.15
  test_split: 0.2
  use_last_target_as_feature: False
  random_state: 
    tune: 1337
  

model_hyperparameters:
  model_class: mdn
  n_hidden: [64,128,128,64]
  use_layer_norm: True
  n_distributions: 35
  dropout_rate: 0.04
  activation_function: relu
  distribution_type: gaussian
  std_stability_mode: softplus
  