config_id: pinball_energy_final
seeds: [42, 43, 44, 45, 46]
data_seed: 0

training_hyperparameters:
  early_stopping_patience: 10
  epochs: 500
  clip_gradient_norm: 4.0
  batch_size: 
    tune: [32, 64, 128, 256]
  use_lr_scheduler: False
  optimizer_hyperparameters:
    lr: 2.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
  optimizer: adam
  input_noise_x: 0.03
  input_noise_y: 0.03
  loss_hyperparameters:
    reliability_loss_weight: 0.0
    weights_entropy_loss_weight: 0.125
    loss_calculation_in_normalised_domain: True
    pinball_loss_weight: 1.0
    nll_loss_weight: 1.0
  eval_metric_for_best_model: val_nll_loss
  evaluation_function_names: [miscalibration, conformal_prediction]
  slow_first_n_batches: 1
  log_train_every_n: 10
  noisy_start: True
  noise_level: 0.3
  noise_decay: 0.3
  n_random_target_swap_per_epoch:
    tune: [0, 100]

data_hyperparameters:
  data_type: rothfuss
  dataset_name: energy
  val_split: 0.15
  test_split: 0.2
  random_state: 
    tune: [1337, 1338, 1339, 1340, 1341]

model_hyperparameters:
  model_class: mdn
  n_hidden: [64, 128, 128, 64]
  n_distributions: 256
  dropout_rate: 0.04
  activation_function: relu
  distribution_type: gaussian
  std_stability_mode: softplus
  use_layer_norm: False
  force_equal_weights: True
  force_equal_std: True
  train_equal_std: True
