config_id: tanh_stability_test
seeds: [0, 1, 2]
data_seed: 0

training_hyperparameters:
  epochs: 150
  batch_size: 128
  optimizer_hyperparameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
  optimizer: Adam
  input_noise_x: 0.1
  input_noise_y: 0.1
  loss_hyperparameters:
    reliability_loss_weight: 0.0

data_hyperparameters:
  data_type: synthetic
  data_path: datasets/simulated_data/gmm
  

model_hyperparameters:
  n_hidden: [32,32]
  n_distributions: 10
  dropout_rate: 0.0
  activation_function: relu
  distribution_type: gaussian
  tanh_std_stability: null