config_id: kmn2
seeds: [42,43,44,45,46]
data_seed: 0

training_hyperparameters:
  eval_metric_for_best_model: val_nll_loss
  epochs: 500
  batch_size: 256
  optimizer_hyperparameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 1.0e-7
  optimizer: Adam
  input_noise_x: 
    tune:  [0.02, 0.05, 0.1, 0.2]
  input_noise_y:
    tune: [0.02, 0.05, 0.1, 0.2]
  loss_hyperparameters:
    reliability_loss_weight: 0.1
    loss_calculation_in_normalised_domain: True

data_hyperparameters:
  data_type: nyctaxi
  data_path: datasets/nyc_taxi_dataset/
  val_split: 0.1
  test_split: 0.1
  original: False
  random_state: 
    tune: [1336,231,132]
  

model_hyperparameters:
  model_class: nf
  n_hidden: [32, 32]
  n_flows:
    tune: [2, 6, 10, 20]
  dropout_rate: 0.0
  activation_function: leaky_relu
  
