config_id: improved_dummy_config
seeds: [0, 1, 2, 3, 4]

training_hyperparameters:
  epochs: 50
  batch_size: 128
  optimizer_hyperparameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
  optimizer: Adam
  input_noise_x: 0.1
  input_noise_y: 0.1
  reliability_loss_weight: 20.0

data_hyperparameters:
  data_type: synthetic
  data_path: datasets/simulated_data/gmm

model_hyperparameters:
  n_hidden: [10,10]
  n_distributions: 10
  dropout_rate: 0.2
  activation_function: relu
  distribution_type: gaussian
