config_id: reproduce_rothfuss4
seeds: [42,43,44]
data_seed: 0

training_hyperparameters:
  epochs: 150
  batch_size: 256
  optimizer_hyperparameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 1.0e-7
  optimizer: Adam
  input_noise_x: 0.2
  input_noise_y: 0.1
  loss_hyperparameters:
    reliability_loss_weight: 0.0
    loss_calculation_in_normalised_domain: True

data_hyperparameters:
  data_type: uci
  dataset_name: 
    tune: [energy_efficiency, boston_housing, concrete]
  val_split: 0.1
  test_split: 0.1
  original: False
  random_state: 
    tune: [1337, 1338, 1339]
  

model_hyperparameters:
  model_class: mdn
  n_hidden: [32, 32]
  n_distributions: 10
  dropout_rate: 0.0
  activation_function: leaky_relu
  distribution_type: gaussian
  std_stability_mode: softplus
  
