config_id: voest_debug
seeds: [3, 4, 5, 6, 7, 8, 9]
data_seed: 0

training_hyperparameters:
  epochs: 150
  batch_size: 128
  optimizer_hyperparameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 1.0e-6
  optimizer: Adam
  input_noise_x: 0.1
  input_noise_y: 0.1
  loss_hyperparameters:
    reliability_loss_weight: 0.0

data_hyperparameters:
  data_type: voest
  data_path: datasets/voest_datasets/
  original: False
  

model_hyperparameters:
  n_hidden: [32,32]
  n_distributions: 10
  dropout_rate: 0.0
  activation_function: relu
  distribution_type: gaussian
